E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] failed while attempting to run meta for aten.bmm.default
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] Traceback (most recent call last):
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_subclasses/fake_tensor.py", line 2384, in _dispatch_impl
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     r = func(*args, **kwargs)
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]         ^^^^^^^^^^^^^^^^^^^^^
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_ops.py", line 723, in __call__
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     return self._op(*args, **kwargs)
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_meta_registrations.py", line 3900, in meta_bmm
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     return common_meta_baddbmm_bmm(self, mat2, True)
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_meta_registrations.py", line 3878, in common_meta_baddbmm_bmm
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     torch._check(
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/__init__.py", line 1656, in _check
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     _check_with(RuntimeError, cond, message)
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/__init__.py", line 1638, in _check_with
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     raise error_type(message_evaluated)
E0204 13:06:31.375000 500878 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [16, 4] but got: [16, 1].
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] failed while attempting to run meta for aten.bmm.default
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] Traceback (most recent call last):
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_subclasses/fake_tensor.py", line 2384, in _dispatch_impl
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     r = func(*args, **kwargs)
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]         ^^^^^^^^^^^^^^^^^^^^^
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_ops.py", line 723, in __call__
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     return self._op(*args, **kwargs)
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_meta_registrations.py", line 3900, in meta_bmm
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     return common_meta_baddbmm_bmm(self, mat2, True)
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/_meta_registrations.py", line 3878, in common_meta_baddbmm_bmm
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     torch._check(
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/__init__.py", line 1656, in _check
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     _check_with(RuntimeError, cond, message)
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]   File "/home/sahanp/.conda/envs/parity-bench/lib/python3.12/site-packages/torch/__init__.py", line 1638, in _check_with
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0]     raise error_type(message_evaluated)
E0205 17:56:48.125000 3236547 site-packages/torch/_subclasses/fake_tensor.py:2388] [0/0] RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [16, 4] but got: [16, 1].
